name: blackrose
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: '>= 4.7.0'
  firebase_core: ^2.8.0
  money_formatter: ^0.0.4
  firebase_auth: ^4.0.0  
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.2
  get: ^4.6.5
  cloud_firestore: ^4.4.5
  provider: ^6.0.5
  badges: ^3.1.0
  tiengviet: ^0.5.0
  
dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/BlackRose_icon.png"
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/banner/
    - assets/icons/category/
    - assets/icons/notify/
    - assets/icons/profile/
    - assets/icons/
    - assets/logo/